"""Auto-generated extended area canonical map.

Sources: 174 DLD master_projects + 258 DLD admin areas + curated non-Dubai + abbreviations.
Regenerate via _phase_ab_expand_canonicals.py.
"""

AREA_CANONICAL_EXTENDED = {
    '800 villas': '800 Villas',
    'abu hail': '',
    'ajman corniche': 'Ajman Corniche',
    'al asbaq': '',
    'al athbah': '',
    'al aweer first': '',
    'al aweer second': '',
    'al bada': '',
    'al baharna': '',
    'al baraha': '',
    'al barari': 'Al Barari',
    'al barsha': '',
    'al barsha 1': 'Al Barsha',
    'al barsha 2': 'Al Barsha',
    'al barsha first': '',
    'al barsha second': '',
    'al barsha south fifth': 'Jumeirah Village Triangle',
    'al barsha south fourth': 'Jumeirah Village Circle',
    'al barsha third': '',
    'al barshaa south first': '',
    'al barshaa south second': 'Dubai Science Park',
    'al barshaa south third': 'Arjan',
    'al bateen': 'Al Bateen',
    'al buteen': '',
    'al dhagaya': '',
    'al eyas': '',
    "al faga'a": '',
    'al fahidi': '',
    'al furjan': 'Al Furjan',
    'al garhoud': '',
    'al ghadeer': 'Al Ghadeer',
    'al goze first': '',
    'al goze fourth': '',
    'al goze industrial first': '',
    'al goze industrial fourth': '',
    'al goze industrial second': '',
    'al goze industrial third': '',
    'al goze third': '',
    'al hamra': 'Al Hamra Village',
    'al hamra village': 'Al Hamra Village',
    'al hamriya': '',
    'al hebiah fifth': 'Remraam',
    'al hebiah first': 'Motor City',
    'al hebiah fourth': 'Dubai Sports City',
    'al hebiah second': 'Dubai Studio City',
    'al hebiah sixth': 'Mudon',
    'al hebiah third': 'DAMAC HILLS',
    'al hudaiba': '',
    'al jadaf': 'Dubai Health Care City Phase 2',
    'al jafliya': '',
    'al karama': '',
    'al khabeesi': '',
    'al khail towers': 'Al Khail Towers',
    'al khairan  second': 'The Lagoons',
    'al khairan first': 'Dubai Creek Harbour',
    'al khawaneej': '',
    'al khawaneej district': 'AL KHAWANEEJ DISTRICT',
    'al khawaneej first': '',
    'al khawaneej labour city': 'Al Khawaneej Labour City',
    'al khawaneej second': '',
    'al kheeran': 'Festival City',
    'al kifaf': 'Wasl 1',
    'al layan1': '',
    'al lusaily': '',
    'al maha': '',
    'al mamzar': 'Al Mamzar',
    'al mamzer': '',
    'al manara': '',
    'al mararr': '',
    'al marjan': 'Al Marjan Island',
    'al marjan island': 'Al Marjan Island',
    'al marmoom': '',
    'al maryah': 'Al Maryah Island',
    'al maryah island': 'Al Maryah Island',
    'al merkadh': 'SOBHA HARTLAND',
    'al mizhar': '',
    'al mizhar first': '',
    'al mizhar fourth': '',
    'al mizhar second': '',
    'al mizhar third': '',
    'al murqabat': '',
    'al musalla (dubai)': '',
    'al mushrif': 'Al Mushrif',
    'al muteena': '',
    'al nahda first': '',
    'al nahda second': '',
    'al qoaz': '',
    'al quoz': 'Al Quoz',
    'al qusais': '',
    'al qusais industrial fifth': '',
    'al qusais industrial first': '',
    'al qusais industrial fourth': '',
    'al qusais industrial second': '',
    'al qusais industrial third': '',
    'al qusais old': '',
    'al raffa': '',
    'al raha': 'Al Raha Beach',
    'al raha beach': 'Al Raha Beach',
    'al ras': '',
    'al rashidiya': 'Al Rashidiya',
    'al reef': 'Al Reef',
    'al reem': 'Al Reem Island',
    'al reem island': 'Al Reem Island',
    'al rega': '',
    'al rowaiyah first': 'Dubai International Academic City',
    'al rowaiyah second': '',
    'al rowaiyah third': '',
    'al ruwayyah': 'The Villa',
    'al sabkha': '',
    'al safa': 'Al Safa',
    'al safaa': '',
    'al saffa first': '',
    'al saffa second': '',
    'al safouh first': 'Sufouh Gardens',
    'al safouh second': 'Site A',
    'al satwa': 'Jumeirah Garden City',
    'al shamkha': 'Al Shamkha',
    'al sufouh': 'Al Sufouh',
    'al suq al kabeer': '',
    'al thanayah fourth': 'Springs - 1',
    'al thanyah fifth': 'DMCC Master Community',
    'al thanyah first': 'Barsha Heights',
    'al thanyah third': 'The Greens',
    'al ttay': 'Al Khawaneej Labour City',
    'al twar fifth': '',
    'al twar first': '',
    'al twar fourth': '',
    'al twar second': '',
    'al twar third': '',
    'al waha villas': 'Al Waha Villas',
    'al waheda': '',
    'al warqa first': '',
    'al warqa fourth': '',
    'al warqa second': '',
    'al warqa third': '',
    'al warsan first': 'International City Phase 1',
    'al warsan industrial': 'AL WARSAN INDUSTRIAL',
    'al warsan second': 'AL WARSAN INDUSTRIAL',
    'al warsan third': '',
    'al wasl': 'City Walk',
    'al wasl district': 'Al Wasl District',
    'al yelayiss 1': '',
    'al yelayiss 2': 'TOWN SQUARE',
    'al yelayiss 3': '',
    'al yelayiss 4': '',
    'al yelayiss 5': '',
    'al yufrah 1': 'The Valley',
    'al yufrah 2': 'DAMAC HILLS 2',
    'al yufrah 3': 'DAMAC HILLS 2',
    'al yufrah 4': '',
    'al zahia': 'Al Zahia',
    'al-aweer': '',
    'al-baloosh': '',
    'al-bastakiyah': '',
    'al-cornich': '',
    'al-dzahiyyah al-jadeedah': '',
    'al-muhaisnah north': '',
    'al-murar jadeed': '',
    'al-murar qadeem': '',
    'al-musalla (deira)': '',
    'al-mustashfa west': '',
    'al-nahdah': '',
    'al-nakhal': '',
    'al-qiyadah': '',
    'al-raulah': '',
    'al-riqqa east': '',
    'al-riqqa west': '',
    'al-safiyyah': '',
    'al-shumaal': '',
    'al-souq al kabeer (deira)': '',
    'al-tawar': '',
    'al-zarouniyyah': '',
    'aljada': 'Aljada',
    'arabian ranches': 'Arabian Ranches',
    'arabian ranches - 1': 'Arabian Ranches - 1',
    'arabian ranches - polo homes': 'Arabian Ranches - Polo Homes',
    'arabian ranches 2': 'Arabian Ranches 2',
    'arabian ranches 3': 'Arabian Ranches 3',
    'arabian ranches ii': 'Arabian Ranches II',
    'arjan': 'Arjan',
    'athlon': 'Athlon',
    'badra': 'Badra',
    'barsha heights': 'Barsha Heights',
    'bb': 'Business Bay',
    'biz bay': 'Business Bay',
    'bluewaters island': 'Bluewaters Island',
    'bukadra': '',
    'bur dubai': '',
    'burj khalifa': 'Burj Khalifa',
    'burj nahar': '',
    'bus bay': 'Business Bay',
    'business bay': 'Business Bay',
    'business park': 'Business Park',
    'city of arabia': 'City Of Arabia',
    'city walk': 'City Walk',
    'cornich deira': '',
    'creek': 'Dubai Creek Harbour',
    'creek harbour': 'Dubai Creek Harbour',
    'culture village': 'Culture Village',
    'damac hills': 'DAMAC HILLS',
    'damac hills 2': 'DAMAC HILLS 2',
    'damac lagoons': 'DAMAC Lagoons',
    'deira': 'Deira',
    'deira islands': 'Deira Islands',
    'dhe': 'Dubai Hills Estate',
    'discovery gardens': 'Discovery Gardens',
    'dmcc master community': 'DMCC Master Community',
    'dmcc-ez2': 'DMCC-EZ2',
    'down town jabal ali': 'Down Town Jabal Ali',
    'downtown dubai': 'DownTown Dubai',
    'dubai creek harbour': 'Dubai Creek Harbour',
    'dubai harbour': 'Dubai Harbour',
    'dubai health care city phase 1': 'Dubai Health Care City Phase 1',
    'dubai health care city phase 2': 'Dubai Health Care City Phase 2',
    'dubai hills': 'DUBAI HILLS',
    'dubai hills - club villas': 'DUBAI HILLS - CLUB VILLAS',
    'dubai hills - emerald hills': 'DUBAI HILLS - EMERALD HILLS',
    'dubai hills - fairway vistas': 'DUBAI HILLS - FAIRWAY VISTAS',
    'dubai hills - fairways': 'DUBAI HILLS - FAIRWAYS',
    'dubai hills - golf grove': 'DUBAI HILLS - GOLF GROVE',
    'dubai hills - golf place': 'DUBAI HILLS - GOLF PLACE',
    'dubai hills - golf terraces': 'DUBAI HILLS - GOLF TERRACES',
    'dubai hills - hills grove': 'DUBAI HILLS - HILLS GROVE',
    'dubai hills - hills view': 'DUBAI HILLS - HILLS VIEW',
    'dubai hills - lambourghini': 'DUBAI HILLS - LAMBOURGHINI',
    'dubai hills - maple 1': 'DUBAI HILLS - MAPLE 1',
    'dubai hills - maple 2': 'DUBAI HILLS - MAPLE 2',
    'dubai hills - maple 3': 'DUBAI HILLS - MAPLE 3',
    'dubai hills - palm hills': 'DUBAI HILLS - PALM HILLS',
    'dubai hills - parkway vistas': 'DUBAI HILLS - PARKWAY VISTAS',
    'dubai hills - parkways': 'DUBAI HILLS - PARKWAYS',
    'dubai hills - sidra 1': 'DUBAI HILLS - SIDRA 1',
    'dubai hills - sidra 2': 'DUBAI HILLS - SIDRA 2',
    'dubai hills - sidra 3': 'DUBAI HILLS - SIDRA 3',
    'dubai hills estate': 'Dubai Hills Estate',
    'dubai industrial city': 'Dubai Industrial City',
    'dubai international academic city': 'Dubai International Academic City',
    'dubai international airport': '',
    'dubai international financial center': 'Dubai International Financial Center',
    'dubai investment park first': 'Dubai Investment Park First',
    'dubai investment park second': 'Dubai Investment Park Second',
    'dubai island': 'Dubai Islands',
    'dubai islands': 'Dubai Islands',
    'dubai land residence complex': 'Dubai Land Residence Complex',
    'dubai life style city': 'Dubai Life Style City',
    'dubai marina': 'Dubai Marina',
    'dubai maritime city': 'Dubai Maritime City',
    'dubai outsource city': 'Dubai Outsource City',
    'dubai science park': 'Dubai Science Park',
    'dubai south residential district': 'Dubai South Residential District',
    'dubai sports city': 'Dubai Sports City',
    'dubai studio city': 'Dubai Studio City',
    'dubai water canal': 'Dubai Water Canal',
    'dubai water front': 'Dubai Water Front',
    'dubai world central': 'Dubai World Central',
    'dubiotech': 'Dubiotech',
    'dxh': 'Dubai Harbour',
    "emaar's street of dreams": "Emaar's Street Of Dreams",
    'emirates city': 'Emirates City',
    'emirates hills': 'Emirates Hills',
    'emirates living': 'Emirates Living',
    'expo city': 'Expo City Dubai',
    'expo city dubai': 'Expo City Dubai',
    'eyal nasser': '',
    'falcon city': 'Falcon City',
    'festival city': 'Festival City',
    'festival city first': 'Festival City',
    'garden view': 'Garden View',
    'garhoud': 'Al Garhoud',
    'ghadeer al tair': '',
    'ghadeer barashy': '',
    'ghaf woods': 'Ghaf Woods',
    'global village': 'Global Village',
    'grayteesah': '',
    'hadaeq sheikh mohammed bin rashid': 'Dubai Hills Estate',
    'hadaeq sheikh mohammed bin rashid - disrict 7': 'HADAEQ SHEIKH MOHAMMED BIN RASHID - DISRICT 7',
    'hatta': '',
    'haven': 'Haven by Aldar',
    'haven aldar': 'Haven by Aldar',
    'hessyan first': 'Badra',
    'hessyan second': 'Dubai Water Front',
    'hor al anz': '',
    'hor al anz east': '',
    'ibn battuta': 'Ibn Battuta',
    'international city phase 1': 'International City Phase 1',
    'international city phase 2': 'International City Phase 2',
    'international city phase 3': 'International City Phase 3',
    'international media production zone': 'International Media Production Zone',
    'island 2': 'Jumeira Bay',
    'jabal ali': 'Discovery Gardens',
    'jabal ali first': 'Al Furjan',
    'jabal ali industrial development': 'JABAL ALI INDUSTRIAL DEVELOPMENT',
    'jabal ali industrial first': 'JABAL ALI INDUSTRIAL DEVELOPMENT',
    'jabal ali industrial second': 'Down Town Jabal Ali',
    'jabal ali industrial third': 'Down Town Jabal Ali',
    'jabal ali third': '',
    'jabal ali village': 'Jabal Ali Village',
    'jabel ali hills': 'JABEL ALI HILLS',
    'jaddaf waterfront': 'Jaddaf Waterfront',
    'jbr': 'Jumeirah Beach Residence',
    'jebel ali village': 'Jebel Ali Village',
    'jge': 'Jumeirah Golf Estates',
    'jumeira bay': 'Jumeira Bay',
    'jumeirah': '',
    'jumeirah first': 'LA MER',
    'jumeirah garden city': 'Jumeirah Garden City',
    'jumeirah golf estates': 'Jumeirah Golf Estates',
    'jumeirah golf estates - phase b': 'Jumeirah Golf Estates - Phase B',
    'jumeirah islands': 'Jumeirah Islands',
    'jumeirah park': 'Jumeirah Park',
    'jumeirah second': '',
    'jumeirah third': '',
    'jumeirah village circle': 'Jumeirah Village Circle',
    'jumeirah village triangle': 'Jumeirah Village Triangle',
    'jumeriah beach residence  - jbr': 'Jumeriah Beach Residence  - JBR',
    'jvc': 'Jumeirah Village Circle',
    'jvt': 'Jumeirah Village Triangle',
    'karama': 'Al Karama',
    'khalifa city': 'Khalifa City',
    'la mer': 'LA MER',
    'lakes - deema 1': 'Lakes - Deema 1',
    'lakes - deema 2': 'Lakes - Deema 2',
    'lakes - deema 3': 'Lakes - Deema 3',
    'lakes - deema 4': 'Lakes - Deema 4',
    'lakes - forat': 'Lakes - Forat',
    'lakes - ghadeer': 'Lakes - Ghadeer',
    'lakes - hattan i': 'Lakes - Hattan I',
    'lakes - hattan ii': 'Lakes - Hattan II',
    'lakes - hattan iii': 'Lakes - Hattan III',
    'lakes - maeen': 'Lakes - Maeen',
    'le hemaira': '',
    'lehbab': '',
    'lehbab first': '',
    'lehbab second': '',
    'living legends': 'Living Legends',
    'liwan': 'Liwan',
    'liwan1': 'Liwan1',
    'liwan2': 'Liwan2',
    'madinat al mataar': 'Dubai World Central',
    'madinat badr': 'Madinat Badr',
    'madinat dubai almelaheyah': 'Dubai Maritime City',
    'madinat hind 1': '',
    'madinat hind 2': '',
    'madinat hind 3': '',
    'madinat hind 4': 'DAMAC HILLS 2',
    'madinat latifa': '',
    'majan': 'Majan',
    'mall of emirates': 'Al Barsha',
    'mankhool': '',
    'mar': 'Dubai Marina',
    'margham': '',
    'marsa dubai': 'Dubai Marina',
    'masdar city': 'Masdar City',
    "me'aisem first": 'International Media Production Zone',
    "me'aisem second": '',
    'meadows 1': 'Meadows 1',
    'meadows 2': 'Meadows 2',
    'meadows 3': 'Meadows 3',
    'meadows 4': 'Meadows 4',
    'meadows 5': 'Meadows 5',
    'meadows 6': 'Meadows 6',
    'meadows 7': 'Meadows 7',
    'meadows 8': 'Meadows 8',
    'meadows 9': 'Meadows 9',
    'mena jabal ali': '',
    'meydan': 'Meydan',
    'meydan one community': 'Meydan One Community',
    'meydan racecourse community': 'Meydan Racecourse Community',
    'mina al arab': 'Mina Al Arab',
    'mina rashid': 'Mina Rashid',
    'miracle garden': 'Arjan',
    'mirdif': '',
    'mohammed bin rashid al maktoum city -district -1 community': 'Mohammed Bin Rashid AL Maktoum City -District -1 Community',
    'mohammed bin rashid al maktoum district 11': 'Mohammed Bin Rashid AL Maktoum District 11',
    'motor city': 'Motor City',
    'muashrah al bahraana': '',
    'mudon': 'Mudon',
    'mugatrah': '',
    'muhaisanah first': 'Madinat Badr',
    'muhaisanah fourth': '',
    'muhaisanah second': '',
    'muhaisanah third': '',
    'muhaisna': '',
    'muragab': '',
    'mushrif': '',
    'muwaileh': 'Muwaileh',
    'nad al hamar': '',
    'nad al sheba gardens': 'Nad Al Sheba Gardens',
    'nad al shiba': 'Silicon Oasis',
    'nad al shiba first': 'Meydan Racecourse Community',
    'nad al shiba fourth': '',
    'nad al shiba second': '',
    'nad al shiba third': 'Nad Al Shiba Villas',
    'nad al shiba villas': 'Nad Al Shiba Villas',
    'nad rashid': '',
    'nad shamma': '',
    'nadd hessa': 'Silicon Oasis',
    'naif': '',
    'naif north': '',
    'naif south': '',
    'nazwah': '',
    'old town': 'Downtown Dubai',
    'old town downtown': 'Downtown Dubai',
    'oud metha': '',
    'palm deira': 'Palm Deira',
    'palm jabal ali': 'Palm Jabal Ali',
    'palm jebel ali': 'Palm Jebel Ali',
    'palm jumeirah': 'Palm Jumeirah',
    'pearl jumeira': 'Pearl Jumeira',
    'port saeed': '',
    'ras al khor': '',
    'ras al khor industrial first': '',
    'ras al khor industrial second': '',
    'ras al khor industrial third': '',
    'reem island': 'Al Reem Island',
    'rega al buteen': '',
    'remah': '',
    'remraam': 'Remraam',
    'residential complex': 'Residential Complex',
    'rukan': 'Rukan',
    'saadiyat': 'Saadiyat Island',
    'saadiyat island': 'Saadiyat Island',
    'saih aldahal': '',
    'saih shuaib 1': 'JABEL ALI HILLS',
    'saih shuaib 2': '',
    'saih shuaib 3': 'Dubai Industrial City',
    'saih shuaib 4': 'Dubai Industrial City',
    'sama al jadaf': 'Sama Al Jadaf',
    'satwa': 'Al Satwa',
    'shandagha east': '',
    'shandagha west': '',
    'sharjah waterfront city': 'Sharjah Waterfront City',
    'sikkat al khail north': '',
    'sikkat al khail south': '',
    'silicon oasis': 'Silicon Oasis',
    'site a': 'Site A',
    'sobha hartland': 'SOBHA HARTLAND',
    'sobha hartland 2': 'Sobha Hartland 2',
    'springs - 1': 'Springs - 1',
    'springs - 2': 'Springs - 2',
    'springs - 3': 'Springs - 3',
    'springs - 4': 'Springs - 4',
    'springs - 5': 'Springs - 5',
    'springs - 6': 'Springs - 6',
    'springs - 7': 'Springs - 7',
    'sufouh gardens': 'Sufouh Gardens',
    'tawaa al sayegh': '',
    'tawi al muraqqab': '',
    'tecom site a': 'TECOM Site A',
    'tecom site b': 'TECOM Site B',
    'tecom site c': 'TECOM Site C',
    'tecom site d': 'TECOM Site D',
    'the gardens': 'The Gardens',
    'the greens': 'The Greens',
    'the heights country club': 'The Heights Country Club & Wellness',
    'the lagoons': 'The Lagoons',
    'the lakes': 'The Lakes',
    'the meadows': 'The Meadows',
    'the oasis': 'The Oasis',
    'the old town': 'Downtown Dubai',
    'the palmarosa': 'The Palmarosa',
    'the springs': 'The Springs',
    'the sustainable city': 'THE SUSTAINABLE CITY',
    'the valley': 'The Valley',
    'the villa': 'The Villa',
    'the world': 'The World',
    'the world islands': 'The World Islands',
    'tijara town': 'Tijara Town',
    'tilal al ghaf': 'TILAL AL GHAF',
    'tilal city': 'Tilal City',
    'town square': 'TOWN SQUARE',
    'trade center first': '',
    'trade center second': '',
    'um al sheif': '',
    'um esalay': '',
    'um hurair first': '',
    'um hurair second': 'Dubai Health Care City Phase 1',
    'um ramool': '',
    'um suqaim': '',
    'um suqaim first': '',
    'um suqaim second': '',
    'um suqaim third': '',
    'umm addamin': '',
    'umm suqeim': 'Umm Suqeim',
    'uptown mirdif': 'Uptown Mirdif',
    'veneto': 'Veneto',
    'wadi al amardi': '',
    'wadi al safa 2': 'Liwan1',
    'wadi al safa 3': 'Majan',
    'wadi al safa 4': '',
    'wadi al safa 5': 'Dubai Land Residence Complex',
    'wadi al safa 6': 'Arabian Ranches - 1',
    'wadi al safa 7': 'Arabian Ranches II',
    'warsan first development': 'WARSAN FIRST DEVELOPMENT',
    'warsan fourth': 'International City Phase 3',
    'wasl 1': 'Wasl 1',
    'wasl gate': 'Wasl Gate',
    'wellness': 'The Heights Country Club & Wellness',
    'world islands': 'The World',
    'yaraah': '',
    'yas': 'Yas Island',
    'yas island': 'Yas Island',
    'zaabeel first': '',
    'zaabeel second': '',
    'zareeba duviya': '',
}
