"""
known_buildings.py — Canonical building/project names for Dubai resale normalization.
Used by rapidfuzz fuzzy matching in resale_bot.py (threshold 75%).
~600 buildings organised by area. All names in Title Case English.
"""

KNOWN_BUILDINGS: list[str] = [
    # ── Downtown Dubai / Burj Khalifa Area ─────────────────────────────────────
    "Burj Khalifa",
    "The Address Downtown",
    "The Address Boulevard",
    "The Address Residences Downtown",
    "The Address Fountain Views",
    "Burj Crown",
    "Burj Royale",
    "Boulevard Point",
    "The Lofts East",
    "The Lofts West",
    "The Lofts Central",
    "8 Boulevard Walk",
    "Vida Dubai Mall",
    "Forte Tower 1",
    "Forte Tower 2",
    "Act One Act Two",
    "The Grande",
    "IL Primo",
    "Bellevue Tower 1",
    "Bellevue Tower 2",
    "Burj Daman",
    "Claren Tower 1",
    "Claren Tower 2",
    "South Ridge Tower 1",
    "South Ridge Tower 2",
    "South Ridge Tower 3",
    "South Ridge Tower 4",
    "29 Boulevard",
    "Executive Tower A",
    "Executive Tower B",
    "Executive Tower G",
    "Boulevard Central Tower 1",
    "Boulevard Central Tower 2",
    "Opera Grand",
    "Fountain Views Tower 1",
    "Fountain Views Tower 2",
    "Fountain Views Tower 3",
    "Standpoint Tower A",
    "Standpoint Tower B",
    "Downtown Views",
    "Downtown Views II",
    "Burj Vista Tower 1",
    "Burj Vista Tower 2",

    # ── Business Bay ────────────────────────────────────────────────────────────
    "DAMAC Maison Prive",
    "DAMAC Maison Canal Views",
    "DAMAC Towers By Paramount",
    "SLS Dubai Hotel & Residences",
    "The Opus",
    "Aykon City Tower A",
    "Aykon City Tower B",
    "Aykon City Tower C",
    "Aykon City Tower D",
    "One Business Bay",
    "Bay's Edge",
    "Capital Bay Tower A",
    "Capital Bay Tower B",
    "Vera Residences",
    "Merano Tower",
    "Ubora Tower 1",
    "Ubora Tower 2",
    "Millennium Binghatti Residences",
    "Amna Tower",
    "Metropolis Tower",
    "Park Central",
    "Windsor Manor",
    "Westburry Tower 1",
    "Westburry Tower 2",
    "Executive Bay",
    "The Sterling East",
    "The Sterling West",
    "Reva Residences",
    "AG Square",
    "Al Habtoor City",
    "Noura Tower",
    "Park Tower",
    "Churchill Residency",
    "Churchill Executive Tower",
    "Saba Tower 1",
    "Saba Tower 2",
    "Saba Tower 3",
    "The Binary Tower",
    "Hamilton Tower",
    "Mayfair Residency",
    "Volante",
    "Elara Residences",
    "Peninsula One",
    "Peninsula Two",
    "Peninsula Three",
    "Peninsula Four",
    "Peninsula Five",

    # ── Dubai Marina ────────────────────────────────────────────────────────────
    "Marina Gate 1",
    "Marina Gate 2",
    "Marina Gate 3",
    "Sulafa Tower",
    "Princess Tower",
    "Elite Residence",
    "Cayan Tower",
    "The Torch",
    "Marina Crown",
    "Silverene Tower A",
    "Silverene Tower B",
    "Horizon Tower",
    "Cascades",
    "Botanica Tower",
    "Al Anbar Tower",
    "Al Fairooz Tower",
    "Mariners Wharf",
    "Grosvenor House",
    "Address Beach Resort",
    "LIV Marina",
    "LIV Residence",
    "Emaar 6 Tower",
    "Saba 1",
    "Saba 2",
    "Saba 3",
    "Paloma Tower",
    "Five Marina",
    "Dubai Marina View Tower 1",
    "Dubai Marina View Tower 2",
    "The Waves Tower A",
    "The Waves Tower B",
    "The Waves Tower C",
    "No 9 Tower",
    "Imperial Residence",
    "Mag 218",
    "Bay Central West",
    "Bay Central East",
    "Marina Diamond 1",
    "Marina Diamond 2",
    "Marina Diamond 3",
    "Marina Diamond 4",
    "Marina Diamond 5",
    "Marina Diamond 6",
    "Marina Terrace",
    "Park Island",
    "Trident Grand",
    "Al Sahab Tower",
    "Shams Abu Dhabi Tower",

    # ── JBR (Jumeirah Beach Residence) ──────────────────────────────────────────
    "Murjan 1",
    "Murjan 2",
    "Murjan 3",
    "Murjan 4",
    "Murjan 5",
    "Murjan 6",
    "Bahar 1",
    "Bahar 2",
    "Bahar 3",
    "Bahar 4",
    "Bahar 5",
    "Bahar 6",
    "Amwaj 1",
    "Amwaj 2",
    "Amwaj 3",
    "Amwaj 4",
    "Rimal 1",
    "Rimal 2",
    "Rimal 3",
    "Rimal 4",
    "Rimal 5",
    "Rimal 6",
    "Shems 1",
    "Shems 2",
    "Shems 3",
    "Shems 4",
    "Sadaf 1",
    "Sadaf 2",
    "Sadaf 3",
    "Sadaf 4",
    "Sadaf 5",
    "Sadaf 6",
    "Sadaf 7",

    # ── Palm Jumeirah ───────────────────────────────────────────────────────────
    "Tiara Residences Aquamarine",
    "Tiara Residences Diamond",
    "Tiara Residences Emerald",
    "Tiara Residences Onyx",
    "Tiara Residences Pearl",
    "Tiara Residences Ruby",
    "Tiara Residences Sapphire",
    "Shoreline Apartments Al Haseer",
    "Shoreline Apartments Al Nabat",
    "Shoreline Apartments Al Anbara",
    "Shoreline Apartments Al Msalli",
    "Shoreline Apartments Al Hamri",
    "Shoreline Apartments Al Khudrawi",
    "Shoreline Apartments Al Mizan",
    "Marina Residences",
    "Signature Villas",
    "One Palm",
    "Atlantis The Royal Residences",
    "FIVE Palm Jumeirah",
    "Fairmont Residences South",
    "Fairmont Residences North",
    "Balqis Residence",
    "Garden Homes Frond A",
    "Garden Homes Frond B",
    "Azure Residences",
    "Serenia Residences",
    "Palme Couture",
    "Palme Royale Row",
    "Ellington Beach House",
    "The 8",
    "Como Residences",
    "Raffles The Palm",
    "Rixos The Palm",

    # ── Dubai Hills Estate ──────────────────────────────────────────────────────
    "Mulberry 1",
    "Mulberry 2",
    "Acacia A",
    "Acacia B",
    "Acacia C",
    "Maple 1",
    "Maple 2",
    "Maple 3",
    "Golf Grove",
    "Sidra 1",
    "Sidra 2",
    "Sidra 3",
    "Ellington House",
    "Ellington House II",
    "Elie Saab Residences",
    "The Park Villas",
    "Mayfair Villas",
    "Collective Tower",
    "Collective 2.0",
    "Golf Heights",
    "Executive Residences 1",
    "Executive Residences 2",
    "Park Heights 1",
    "Park Heights 2",
    "Vida Residences Dubai Hills",
    "Lime Gardens",
    "The Hills",
    "Club Villas",
    "Emerald Hills",
    "Parkway Vistas",
    "Elvira Tower 1",
    "Elvira Tower 2",

    # ── Dubai Creek Harbour ──────────────────────────────────────────────────────
    "Creek Gate Tower 1",
    "Creek Gate Tower 2",
    "The Cove Building 1",
    "The Cove Building 2",
    "The Cove II Building 1",
    "The Cove II Building 2",
    "Surf Tower 1",
    "Surf Tower 2",
    "Creek Rise Tower 1",
    "Creek Rise Tower 2",
    "Creek Horizon Tower 1",
    "Creek Horizon Tower 2",
    "Harbour Views Tower 1",
    "Harbour Views Tower 2",
    "Lotus Tower",
    "Palace Residences",
    "Palace Residences North",
    "Address Harbour Point Tower 1",
    "Address Harbour Point Tower 2",
    "Vida Creek Harbour",
    "Creek Edge Tower 1",
    "Creek Edge Tower 2",
    "Island Park Tower 1",
    "Island Park Tower 2",
    "Orchid",
    "Lotus",
    "Canopy Tower 1",
    "Canopy Tower 2",

    # ── Jumeirah Village Circle (JVC) ────────────────────────────────────────────
    "Binghatti Stars",
    "Binghatti Gateway",
    "Binghatti Avenue",
    "Binghatti Crest",
    "Binghatti Luna",
    "Binghatti Apex",
    "Bloom Towers A",
    "Bloom Towers B",
    "Bloom Towers C",
    "Plazzo Residence",
    "La Fontana Apartments",
    "Empire Suites",
    "Genesis Residences",
    "Belgravia 1",
    "Belgravia 2",
    "Belgravia Heights",
    "Belgravia Square",
    "Loci Residences",
    "Diamond Views 1",
    "Diamond Views 2",
    "Diamond Views 3",
    "Diamond Views 4",
    "Golf Views",
    "Golf Views Seven City",
    "Seasons Community Tower A",
    "Seasons Community Tower B",
    "Gemz by Danube",
    "Park Heights 1 JVC",
    "Park Heights 2 JVC",
    "Celestia",
    "Westar Vista",
    "Warda Apartments",
    "Pantheon Elysee",
    "Pantheon Elysee 2",
    "Nakheel Square",
    "Spica Residences",
    "Vera Residences JVC",
    "Circle Residences",
    "The Imperial Residence JVC",
    "Glitz Residence 1",
    "Glitz Residence 2",
    "Glitz Residence 3",
    "Elite Sports Residence",
    "Sobha Verde",
    "Vincitore Palacio",
    "La Jolla Residences",

    # ── Sobha Hartland / MBR City ────────────────────────────────────────────────
    "Sobha Creek Vistas Tower A",
    "Sobha Creek Vistas Tower B",
    "Sobha Creek Vistas Reserve",
    "Sobha Creek Vistas Grande",
    "Sobha One Tower A",
    "Sobha One Tower B",
    "Sobha One Tower C",
    "Sobha One Tower D",
    "Sobha One Tower E",
    "Sobha Hartland Greens",
    "Hartland Estates",
    "One Park Avenue",
    "Forest Villas",
    "District One Residences",
    "District One Villa",
    "Meydan One Mall Residences",
    "Millennium Estates",
    "Grand Views",
    "Polo Townhouses",
    "Azizi Riviera",
    "Riviera Tower",

    # ── Emaar South / Dubai South ────────────────────────────────────────────────
    "Golf Links",
    "Golf Links Emaar South",
    "Fairway Villas",
    "Greenview",
    "Greenview 2",
    "Expo Valley",
    "Urbana 1",
    "Urbana 2",
    "Urbana 3",
    "Golf Lane",
    "Maple At Dubai Hills",

    # ── Al Furjan ────────────────────────────────────────────────────────────────
    "Azizi Amber",
    "Azizi Aura",
    "Azizi Berton",
    "Azizi Daisy",
    "Azizi Farishta",
    "Azizi Feirouz",
    "Azizi Grand",
    "Azizi Liatris",
    "Azizi Orchid",
    "Azizi Pearl",
    "Azizi Plaza",
    "Azizi Roy Mediterranean",
    "Azizi Star",
    "Azizi Tulip",
    "Azizi Yasamine",
    "Discovery Gardens",
    "The Dreamz",
    "Murooj Al Furjan",
    "Quortaj",
    "Centurion Star",

    # ── DAMAC Hills ─────────────────────────────────────────────────────────────
    "Celestia DAMAC Hills",
    "Golf Promenade 1",
    "Golf Promenade 2",
    "Golf Promenade 3",
    "Golf Promenade 4",
    "Golf Promenade 5",
    "Golf Veduta A",
    "Golf Veduta B",
    "Topanga",
    "Loreto 1A",
    "Loreto 1B",
    "Loreto 2A",
    "Loreto 2B",
    "Loreto 3A",
    "Loreto 3B",
    "Lago Vista",
    "Artesia A",
    "Artesia B",
    "Artesia C",
    "Artesia D",
    "Park Trails",
    "Park Greens",
    "Radisson Dubai Damac Hills",

    # ── Arjan / Al Barsha ────────────────────────────────────────────────────────
    "Vincitore Boulevard",
    "Samana Hills",
    "Samana Skyros",
    "Samana Park Views",
    "Samana Miami",
    "Marquise Square",
    "Azizi Mirage",
    "Azizi Aura Arjan",
    "Westwood Grand",
    "Oxford Terraces",

    # ── Silicon Oasis ────────────────────────────────────────────────────────────
    "Arabian Gates",
    "Cedre Villas",
    "Oasis High Park Tower",
    "Oasis Residences",
    "Radius Residences",
    "Axis Residence 1",
    "Axis Residence 2",
    "Axis Residence 3",
    "Axis Residence 4",
    "Oxford Residence",
    "Silicon Plaza",
    "Semmer Villas",

    # ── Meydan / Nad Al Sheba ────────────────────────────────────────────────────
    "Azizi Riviera Block 1",
    "Azizi Riviera Block 2",
    "Azizi Riviera Block 3",
    "Azizi Riviera Block 4",
    "Azizi Riviera Block 5",
    "Azizi Riviera Block 6",
    "Azizi Riviera Block 7",
    "Azizi Riviera Block 8",
    "Azizi Riviera Block 9",
    "Azizi Riviera Block 10",
    "Azizi Riviera Block 11",
    "Azizi Riviera Block 12",
    "Azizi Riviera Block 13",
    "Azizi Riviera Block 14",
    "Azizi Riviera Block 15",
    "Azizi Riviera Block 16",
    "Azizi Riviera Block 17",
    "Azizi Riviera Block 18",
    "Azizi Riviera Block 19",
    "Azizi Riviera Block 20",
    "Azizi Riviera Beachfront",
    "Lagoons Tower",
    "The Polo Residence",

    # ── Sports City / Motor City ─────────────────────────────────────────────────
    "Olympic Park Tower 1",
    "Olympic Park Tower 2",
    "Olympic Park Tower 3",
    "Olympic Park Tower 4",
    "Olympic Park Tower 5",
    "Olympic Park Tower 6",
    "Sport Tower",
    "Manchester Tower",
    "Elite Sports Residence 1",
    "Elite Sports Residence 2",
    "Elite Sports Residence 3",
    "Elite Sports Residence 4",
    "Elite Sports Residence 5",
    "Elite Sports Residence 6",
    "Elite Sports Residence 7",
    "Elite Sports Residence 8",
    "Elite Sports Residence 9",
    "Elite Sports Residence 10",
    "Spyglass Tower",
    "Lakeside Tower A",
    "Lakeside Tower B",
    "Lakeside Tower C",
    "Lakeside Tower D",
    "Golf Tower 1",
    "Golf Tower 2",
    "Golf Tower 3",
    "Victory Heights",
    "Park Place",
    "Bloomingdale Villas",

    # ── International City ───────────────────────────────────────────────────────
    "Morocco Cluster",
    "England Cluster",
    "France Cluster",
    "Spain Cluster",
    "Italy Cluster",
    "Greece Cluster",
    "Emirates Cluster",
    "Persia Cluster",
    "China Cluster",
    "Russia Cluster",
    "Warsan Village",

    # ── City Walk / Jumeirah / La Mer ────────────────────────────────────────────
    "Jumeirah Heights",
    "Jumeirah Bay Island",
    "Bulgari Residences",
    "Bulgari Resort",
    "The Terraces",
    "City Walk Residences",
    "City Walk Building 1",
    "City Walk Building 2",
    "City Walk Building 3",
    "City Walk Building 4",
    "City Walk Building 5",
    "City Walk Building 6",
    "Lamaa Madinat Jumeirah Living",
    "Jomana Madinat Jumeirah Living",
    "Al Jazi Madinat Jumeirah Living",
    "Rahaal Madinat Jumeirah Living",
    "Asayel Madinat Jumeirah Living",
    "Sur La Mer",

    # ── Bluewaters Island ────────────────────────────────────────────────────────
    "Bluewaters Residences Building 1",
    "Bluewaters Residences Building 2",
    "Bluewaters Residences Building 3",
    "Bluewaters Residences Building 4",
    "Bluewaters Residences Building 5",
    "Bluewaters Residences Building 6",
    "Bluewaters Residences Building 7",
    "Bluewaters Residences Building 8",
    "Bluewaters Residences Building 9",
    "Bluewaters Residences Building 10",

    # ── DIFC / Trade Centre Area ─────────────────────────────────────────────────
    "Park Place DIFC",
    "Index Tower",
    "Sky Gardens",
    "Central Park Tower",
    "Burj Daman DIFC",
    "Currency House Tower 1",
    "Currency House Tower 2",
    "Emirates Financial Towers",
    "Gate District",
    "Rove DIFC",

    # ── Dubai Harbour ────────────────────────────────────────────────────────────
    "Dubai Harbour Residences",
    "Emaar Beachfront Tower 1",
    "Emaar Beachfront Tower 2",
    "Emaar Beachfront Tower 3",
    "Beach Mansion Tower 1",
    "Beach Mansion Tower 2",
    "Beach Vista Tower 1",
    "Beach Vista Tower 2",
    "South Beach Residences",
    "Grand Bleu Tower 1",
    "Grand Bleu Tower 2",
    "Address Beach Resort Harbour",

    # ── The Valley / Dubailand ───────────────────────────────────────────────────
    "Elora The Valley",
    "Nara The Valley",
    "Eden The Valley",
    "Orania The Valley",
    "Rivana The Valley",
    "Damac Lagoons Malta",
    "Damac Lagoons Venice",
    "Damac Lagoons Nice",
    "Damac Lagoons Morocco",
    "Damac Lagoons Santorini",
    "Damac Lagoons Portofino",
    "Damac Lagoons Costa Brava",
    "Damac Lagoons Ibiza",
    "Damac Lagoons Marbella",
    "Damac Lagoons Mykonos",
    "Tilal Al Ghaf Harmony",
    "Tilal Al Ghaf Serenity",
    "Majid Al Futtaim Tilal",

    # ── Jumeirah Village Triangle (JVT) ─────────────────────────────────────────
    "District 1A",
    "District 1B",
    "District 1C",
    "District 1D",
    "District 1E",
    "District 2A",
    "District 2B",
    "District 2C",
    "Sycamore",
    "Indigo Tower",
    "Green Park Villas",

    # ── Barsha Heights / TECOM ───────────────────────────────────────────────────
    "Icon Tower 1",
    "Icon Tower 2",
    "Tamani Hotel Marina",
    "Jormand Suites",
    "Bonnington Tower",
    "Shams Residence",
    "Barsha 338",
    "Tulip Creek Hotel Apartments",
    "Studio One Hotel Dubai",
    "Manzil Downtown",

    # ── Yas Island (Abu Dhabi) ───────────────────────────────────────────────────
    "Yas Acres",
    "Ansam",
    "Mayan",
    "Noya",
    "Water's Edge",
    "The Bridges",
    "Reflections",
    "West Yas",
    "Gardenia Bay",
    "Perla",

    # ── Al Reem Island (Abu Dhabi) ───────────────────────────────────────────────
    "City Of Lights Gate Tower 1",
    "City Of Lights Gate Tower 2",
    "City Of Lights Gate Tower 3",
    "Sigma Towers",
    "Tamouh Tower",
    "Marina Square Tower 1",
    "Marina Square Tower 2",
    "Mangrove Place",
    "Reeman Living",
    "Al Maryah Vista",

    # ── Saadiyat Island (Abu Dhabi) ──────────────────────────────────────────────
    "Jawaher Saadiyat",
    "Nudra",
    "Soul Beach",
    "Mamsha Al Saadiyat",
    "Louvre Abu Dhabi Residences",

    # ── Ras Al Khaimah ───────────────────────────────────────────────────────────
    "Mina Al Arab Gateway",
    "Bay Residences RAK",
    "Al Hamra Village",
    "Al Hamra Palace",
    "Bab Al Bahr",
    "Pacific Beach Residence",
    "Marbella Villas RAK",
    "The Lagoon",
    "One Bedroom RAK Beach",
    "Anantara Mina Al Arab",

    # ── Misc / Multi-area developments ───────────────────────────────────────────
    "Creek Beach Surf",
    "Creek Beach Lotus",
    "Creek Beach Canopy",
    "Creek Beach Orchid",
    "Emaar Creek Side",
    "Hills Park",
    "La Rosa",
    "Camelia",
    "Amaranta",
    "Mudon Al Ranim",
    "Ruba Arabian Ranches",
    "Yara Arabian Ranches",
    "Anya Arabian Ranches",
    "Elie Saab Emirates Hills",
    "Address Residences",
    "Vida Residence Downtown",
    "Vida Residence JVT",
    "Vida Residence The Hills",
    "Crest Grande",
    "Crest Avenues",
    "Waves Grande",
    "Harbour Gate",
    "Binghatti Hills",
    "Binghatti Onyx",
    "Binghatti House",
    "Samana Park Views 2",
    "Park One",
    "Knightsbridge",
    "Tonino Lamborghini Residences",
    "Bugatti Residences",
    "The Ritz Carlton Residences",
    "Four Seasons Private Residences",
    "Rixos Premium Residences",
    "Nikki Beach Resort & Spa",
    "Utopia Damac Bay",
    "Cavalli Tower",
    "Damac Bay By Cavalli",
    "Six Senses The Palm",
    "Armani Beach Residences",
    "Muraba Residences",
]

# Flat lower-case index for fast O(1) exact lookup before fuzzy
_BUILDINGS_LOWER: dict[str, str] = {b.lower(): b for b in KNOWN_BUILDINGS}


def normalize_building(raw: str, threshold: int = 70) -> str:
    """
    Return the canonical building name if fuzzy score >= threshold, else raw.
    1. Exact (case-insensitive) match first — O(1).
    2. rapidfuzz WRatio for fuzzy — only if len(raw) >= 5.
    """
    if not raw or len(raw) < 5:
        return raw
    # Fast exact match
    low = raw.strip().lower()
    exact = _BUILDINGS_LOWER.get(low)
    if exact:
        return exact
    # Fuzzy match
    try:
        from rapidfuzz import process as rfp, fuzz
        match = rfp.extractOne(
            raw,
            KNOWN_BUILDINGS,
            scorer=fuzz.WRatio,
            score_cutoff=threshold,
        )
        if match:
            return match[0]  # canonical name
    except Exception:
        pass
    return raw
