"""Auto-documentation pipeline (Level 6 of PHASE BL).

Parses git commits, classifies them via shared LLM chain, and routes
content into:
  - bug_knowledge_base.md (auto B0XX entries from fix commits)
  - README.md (sections from feature commits)
  - CHANGELOG.md (always)
  - ECOSYSTEM_CONTRACTS.md (schema changes)

Append-only. Never deletes. All LLM-generated content is quoted with
"Auto-generated by Claude on YYYY-MM-DD" marker.

If LLM unavailable -> log warning, skip silently (fail-open).
"""
