"""Append B0XX entry to bug_knowledge_base.md from a bugfix commit."""
from __future__ import annotations
import os
import re
from datetime import datetime
from typing import Optional

from . import llm_client


BUG_KB_PATH = os.environ.get(
    "BUG_KB_PATH",
    r"C:\Users\Вадим\.claude\projects\C--Cloude-code\memory\bug_knowledge_base.md",
)


def _next_id(text: str) -> str:
    ids = re.findall(r"###\s*B(\d{3})", text)
    n = max((int(x) for x in ids), default=0) + 1
    return f"B{n:03d}"


def already_indexed(commit_hash: str) -> bool:
    if not os.path.isfile(BUG_KB_PATH):
        return False
    try:
        with open(BUG_KB_PATH, "r", encoding="utf-8") as f:
            return commit_hash[:7] in f.read()
    except Exception:
        return False


_TEMPLATE_PROMPT = """You are documenting a bugfix into a project bug knowledge base.
Output STRICTLY the markdown body below (no preamble, no fences). Keep each
bullet on a SINGLE line. Use the data from commit message + diff.

Format:
### {bug_id}: <short title> ({date})
- **Symptom**: <one line, what user/system saw>
- **Root cause**: <one line, why it happened>
- **Fix**: <one line, what was changed, include file:line if visible>
- **Where else**: <one line, other places to check, or "n/a">
- **Cascading**: <one line, downstream effects, or "n/a">
- **Lesson**: <one line, principle to remember>
- **Commit**: `{short_hash}` (auto-generated by Claude on {date})

Commit message:
{message}

Diff stats:
{diff}

Markdown:"""


def build_entry(commit_hash: str, message: str, diff: str, bug_id: str) -> Optional[str]:
    date = datetime.now().strftime("%Y-%m-%d")
    prompt = (
        _TEMPLATE_PROMPT
        .replace("{bug_id}", bug_id)
        .replace("{date}", date)
        .replace("{short_hash}", commit_hash[:7])
        .replace("{message}", (message or "")[:2000])
        .replace("{diff}", (diff or "")[:3000])
    )
    body = llm_client.llm_call(prompt, max_tokens=600, timeout=25)
    if not body:
        # Fallback skeleton so we still record the fix.
        first_line = (message or "").splitlines()[0] if message else "(no message)"
        return (
            f"### {bug_id}: {first_line} ({date})\n"
            f"- **Symptom**: (auto-stub; LLM unavailable)\n"
            f"- **Root cause**: see commit `{commit_hash[:7]}`\n"
            f"- **Fix**: see commit `{commit_hash[:7]}`\n"
            f"- **Where else**: n/a\n"
            f"- **Cascading**: n/a\n"
            f"- **Lesson**: (auto-stub)\n"
            f"- **Commit**: `{commit_hash[:7]}` (auto-generated by Claude on {date})\n"
        )
    return body.strip() + "\n"


def add_entry(commit_hash: str, message: str, diff: str) -> Optional[str]:
    """Append a new B0XX entry. Returns the entry text or None on no-op."""
    if already_indexed(commit_hash):
        return None
    if not os.path.isfile(BUG_KB_PATH):
        # Don't create the KB out of nowhere — just no-op.
        return None
    with open(BUG_KB_PATH, "r", encoding="utf-8") as f:
        text = f.read()
    bug_id = _next_id(text)
    entry = build_entry(commit_hash, message, diff, bug_id)
    if not entry:
        return None
    # Insert BEFORE the "## Шаблон новой записи" marker if present, otherwise append.
    marker = "## Шаблон новой записи"
    insertion = "\n" + entry + "\n"
    if marker in text:
        new_text = text.replace(marker, insertion + marker, 1)
    else:
        sep = "" if text.endswith("\n") else "\n"
        new_text = text + sep + insertion
    with open(BUG_KB_PATH, "w", encoding="utf-8") as f:
        f.write(new_text)
    return entry
