"""Maintain CHANGELOG.md in the commit's repo (Keep-a-Changelog style)."""
from __future__ import annotations
import os
import re
from datetime import datetime
from typing import Dict


_HEADER = "# Changelog\n\nAuto-generated by Claude (PHASE BL Level 6).\n\n"

_SECTION_BY_TYPE = {
    "bugfix": "Fixed",
    "feature": "Added",
    "refactor": "Changed",
    "schema": "Changed",
    "docs": "Docs",
    "test": "Tests",
    "chore": "Chore",
}


def _first_line(msg: str) -> str:
    return (msg or "").splitlines()[0].strip() if msg else "(no message)"


def append(repo_dir: str, commit_hash: str, message: str, classification: Dict[str, str]) -> str:
    """Add a bullet under today's heading. Creates CHANGELOG.md if absent."""
    path = os.path.join(repo_dir, "CHANGELOG.md")
    if os.path.isfile(path):
        with open(path, "r", encoding="utf-8") as f:
            text = f.read()
    else:
        text = _HEADER
    if commit_hash[:7] in text:
        return path
    today = datetime.now().strftime("%Y-%m-%d")
    heading = f"## [{today}]"
    section = _SECTION_BY_TYPE.get(classification.get("type", "chore"), "Chore")
    bullet = f"- `{commit_hash[:7]}` {_first_line(message)}"

    if heading in text:
        # Insert into existing day block.
        # Find day block boundaries.
        idx = text.index(heading)
        # End of this day block = next "## [" or EOF.
        next_match = re.search(r"\n##\s*\[", text[idx + len(heading):])
        end = idx + len(heading) + (next_match.start() if next_match else len(text) - idx - len(heading))
        block = text[idx:end]
        sub = f"### {section}"
        if sub in block:
            new_block = block.replace(sub, sub + "\n" + bullet, 1)
        else:
            new_block = block.rstrip() + f"\n\n{sub}\n{bullet}\n"
        new_text = text[:idx] + new_block + text[end:]
    else:
        new_block = f"\n{heading}\n### {section}\n{bullet}\n"
        # Insert after header (find first existing "## [" or append).
        m = re.search(r"^##\s*\[", text, re.M)
        if m:
            new_text = text[:m.start()] + new_block + "\n" + text[m.start():]
        else:
            sep = "" if text.endswith("\n") else "\n"
            new_text = text + sep + new_block

    with open(path, "w", encoding="utf-8") as f:
        f.write(new_text)
    return path
