"""Append schema-change notes to ECOSYSTEM_CONTRACTS.md.

Detects CREATE TABLE / ALTER TABLE / DROP TABLE in the diff and records
them under a "## Schema Drift Log (auto)" section. Never removes existing
entries — only marks deprecated.
"""
from __future__ import annotations
import os
import re
from datetime import datetime
from typing import List, Optional


CONTRACTS_PATH = os.environ.get(
    "CONTRACTS_PATH", "C:/Projects/shared/ECOSYSTEM_CONTRACTS.md"
)


_DDL_RE = re.compile(
    r"(?P<op>CREATE\s+TABLE(?:\s+IF\s+NOT\s+EXISTS)?|ALTER\s+TABLE|DROP\s+TABLE)\s+"
    r"(?:IF\s+EXISTS\s+)?[`\"]?(?P<table>[A-Za-z_][\w]*)[`\"]?",
    re.IGNORECASE,
)


def extract_ddl(diff: str) -> List[dict]:
    out = []
    seen = set()
    for m in _DDL_RE.finditer(diff or ""):
        op = re.sub(r"\s+", " ", m.group("op").upper())
        table = m.group("table")
        key = (op, table)
        if key in seen:
            continue
        seen.add(key)
        out.append({"op": op, "table": table})
    return out


def update(commit_hash: str, diff: str) -> Optional[str]:
    ddls = extract_ddl(diff)
    if not ddls:
        return None
    if not os.path.isfile(CONTRACTS_PATH):
        return None
    with open(CONTRACTS_PATH, "r", encoding="utf-8") as f:
        text = f.read()
    if commit_hash[:7] in text:
        return None
    date = datetime.now().strftime("%Y-%m-%d")
    marker = "## Schema Drift Log (auto)"
    lines = [f"- {date} `{commit_hash[:7]}` **{d['op']}** `{d['table']}`" for d in ddls]
    block = "\n".join(lines) + "\n"
    if marker in text:
        new_text = text.replace(marker, marker + "\n" + block, 1)
    else:
        sep = "" if text.endswith("\n") else "\n"
        new_text = (
            text + sep + "\n" + marker + "\n"
            + "Auto-generated by Claude (PHASE BL Level 6). Append-only.\n\n"
            + block
        )
    with open(CONTRACTS_PATH, "w", encoding="utf-8") as f:
        f.write(new_text)
    return block
