"""Append a brief "What's new" section to README.md for feature commits.

Operates on the README in the commit's repo (cwd of the post-commit hook).
Append-only.
"""
from __future__ import annotations
import os
from datetime import datetime
from typing import Optional

from . import llm_client


_PROMPT = """Write a SHORT markdown section (3-6 lines) documenting a new feature.
No preamble, no code fences. Format:

### <feature name> (<date>)
- What: <one line>
- Use: <one line user-facing usage>
- Refs: `<file:line>` (auto-generated by Claude on <date>)

Commit message:
{message}

Diff stats:
{diff}

Markdown:"""


def find_readme(repo_dir: str) -> Optional[str]:
    for name in ("README.md", "Readme.md", "readme.md"):
        p = os.path.join(repo_dir, name)
        if os.path.isfile(p):
            return p
    return None


def add_section(repo_dir: str, commit_hash: str, message: str, diff: str) -> Optional[str]:
    readme = find_readme(repo_dir)
    if not readme:
        return None
    with open(readme, "r", encoding="utf-8") as f:
        text = f.read()
    if commit_hash[:7] in text:
        return None
    date = datetime.now().strftime("%Y-%m-%d")
    prompt = (
        _PROMPT
        .replace("{message}", (message or "")[:1500])
        .replace("{diff}", (diff or "")[:2000])
    )
    body = llm_client.llm_call(prompt, max_tokens=300, timeout=20)
    if not body:
        first_line = (message or "(feature)").splitlines()[0]
        body = (
            f"### {first_line} ({date})\n"
            f"- Commit: `{commit_hash[:7]}` (auto-generated by Claude on {date})\n"
        )
    section = "\n## What's New (auto)\n\n" + body.strip() + "\n"
    # Append at end (append-only; never edit user content).
    sep = "" if text.endswith("\n") else "\n"
    new_text = text + sep + section
    with open(readme, "w", encoding="utf-8") as f:
        f.write(new_text)
    return section
