# Auto-generated by _sync_to_bots.py — DO NOT EDIT manually.
# Adds this directory to sys.path so legacy flat imports
# (e.g. `from causal_engine import ...`) resolve to shared/*.
import os, sys
_here = os.path.dirname(os.path.abspath(__file__))
if _here not in sys.path:
    sys.path.insert(0, _here)
