"""Generate a pytest regression test from a bugfix commit.

LLM produces a self-contained test that:
  - imports nothing requiring DB connections at module-import time,
  - mocks psycopg2/requests where appropriate,
  - reproduces the bug symptom via assertions.

Fail-open: returns None and skips if LLM unavailable.
"""
from __future__ import annotations
import os
import re
import sys
from datetime import datetime
from typing import Optional

_HERE = os.path.dirname(os.path.abspath(__file__))
_PARENT = os.path.dirname(_HERE)
if _PARENT not in sys.path:
    sys.path.insert(0, _PARENT)

from auto_docs import llm_client  # noqa: E402


TESTS_DIR = os.path.join(_HERE, "tests")


_PROMPT = """You generate ONE Python pytest file documenting a regression test
for a bugfix. Hard requirements:

1. Output ONLY valid Python — no markdown fences, no commentary.
2. Test must be IDEMPOTENT (no side effects).
3. NEVER import live DB clients without mocking. Use unittest.mock.patch
   for psycopg2.connect, requests.get/post, etc.
4. If the target module cannot be imported (path not in sys.path),
   use pytest.importorskip("module_name") and skip the test cleanly.
5. Test name: test_b{bug_id_num}_<short_slug>.
6. Top-level docstring includes bug id, commit hash, date.

Commit message:
{message}

Diff stats:
{diff}

Bug id: {bug_id}
Commit hash (short): {short_hash}
Date: {date}

Python pytest file:"""


def _slug(message: str) -> str:
    s = re.sub(r"[^a-zA-Z0-9]+", "_", (message or "fix").splitlines()[0].lower())
    s = s.strip("_")[:40]
    return s or "regression"


def _strip_fences(text: str) -> str:
    """Strip ``` fences if the LLM added them despite instructions."""
    t = text.strip()
    if t.startswith("```"):
        # Remove leading fence (with optional lang).
        t = re.sub(r"^```[a-zA-Z]*\n", "", t)
        # Remove trailing fence.
        t = re.sub(r"\n```\s*$", "", t)
    return t


def _fallback(bug_id: str, slug: str, short_hash: str, message: str, date: str) -> str:
    safe_msg = (message or "").replace('"""', "'''")[:400]
    return f'''"""Regression test for {bug_id} (commit {short_hash}, {date}).

Auto-generated by Claude — LLM unavailable, this is a placeholder
that records the bug existed but does not yet reproduce it.

Original commit message:
{safe_msg}
"""
import pytest


@pytest.mark.skip(reason="auto-stub: LLM unavailable when generated; fill in manually")
def test_{bug_id.lower()}_{slug}_stub():
    assert True
'''


def generate(commit_hash: str, message: str, diff: str, bug_id: str) -> Optional[str]:
    """Generate and write a test file. Returns its path or None."""
    os.makedirs(TESTS_DIR, exist_ok=True)
    # Ensure tests dir is a package.
    init_path = os.path.join(TESTS_DIR, "__init__.py")
    if not os.path.isfile(init_path):
        with open(init_path, "w", encoding="utf-8") as f:
            f.write("")

    date = datetime.now().strftime("%Y-%m-%d")
    slug = _slug(message)
    short_hash = commit_hash[:7]
    filename = f"test_{bug_id.lower()}_{slug}.py"
    path = os.path.join(TESTS_DIR, filename)
    if os.path.exists(path):
        return path  # idempotent

    bug_num = bug_id.lstrip("Bb").lstrip("0") or "0"
    prompt = (
        _PROMPT
        .replace("{message}", (message or "")[:1800])
        .replace("{diff}", (diff or "")[:2500])
        .replace("{bug_id}", bug_id)
        .replace("{bug_id_num}", bug_num)
        .replace("{short_hash}", short_hash)
        .replace("{date}", date)
    )
    code = llm_client.llm_call(prompt, max_tokens=900, timeout=30)
    if code:
        code = _strip_fences(code)
        # Quick sanity: must contain `def test_`.
        if "def test_" not in code:
            code = None
    if not code:
        code = _fallback(bug_id, slug, short_hash, message, date)

    # Compile check — if it fails, fall back to stub.
    try:
        compile(code, filename, "exec")
    except SyntaxError:
        code = _fallback(bug_id, slug, short_hash, message, date)

    with open(path, "w", encoding="utf-8") as f:
        f.write(code)
    return path
